// GENERATED by agent-canvas-core — do not edit by hand.
// Regenerate: cargo test -p agent-canvas-core layout_spec::tests::swift_matches_committed -- --ignored
// or: just gen-layout-spec

import CoreGraphics

/// Portable layout constants from Rust `layout_spec`.
enum LayoutSpec {
    static let version: Int = 1

    static let dropPriority: [String: Int] = [
        "header": 10,
        "metrics": 20,
        "list": 40,
        "chart": 30,
        "text": 50,
        "image": 60,
        "spacer": 70,
        "progress": 45,
        "divider": 75,
        "keyValue": 42,
        "badges": 48,
        "group": 55,
    ]

    static let packRank: [String: Int] = [
        "header": 0,
        "metrics": 1,
        "list": 2,
        "chart": 3,
        "text": 4,
        "image": 5,
        "spacer": 6,
        "progress": 4,
        "divider": 6,
        "keyValue": 2,
        "badges": 4,
        "group": 2,
    ]

    struct Size {
        let tileWidth: CGFloat
        let tileHeight: CGFloat
        let edgeInset: CGFloat
        let sectionSpacing: CGFloat
        let listItemCap: Int
        let maxCharts: Int
        let maxMetrics: Int
        let maxTextChars: Int
        let listRowHeight: CGFloat
        let listTitleHeight: CGFloat
        let chartPlotHeight: CGFloat
        let chartHeightScale: CGFloat
        let metricsHeight: CGFloat
        let headerHeightNoSubtitle: CGFloat
        let headerHeightWithSubtitle: CGFloat
        let textHeight: CGFloat
        let imageHeight: CGFloat
        let spacerHeight: CGFloat
        let progressHeight: CGFloat
        let dividerHeight: CGFloat
        let keyValueRowHeight: CGFloat
        let badgesHeight: CGFloat
        let titleChromeHeight: CGFloat
        let overflowLineHeight: CGFloat
        let timestampHeight: CGFloat
    }

    static func size(_ s: CanvasSize) -> Size {
        switch s {
        case .sm:
            return Size(
                tileWidth: 170,
                tileHeight: 170,
                edgeInset: 12,
                sectionSpacing: 5,
                listItemCap: 5,
                maxCharts: 0,
                maxMetrics: 2,
                maxTextChars: 80,
                listRowHeight: 16,
                listTitleHeight: 14,
                chartPlotHeight: 36,
                chartHeightScale: 0.9,
                metricsHeight: 26,
                headerHeightNoSubtitle: 16,
                headerHeightWithSubtitle: 24,
                textHeight: 26,
                imageHeight: 16,
                spacerHeight: 4,
                progressHeight: 18,
                dividerHeight: 8,
                keyValueRowHeight: 16,
                badgesHeight: 20,
                titleChromeHeight: 16,
                overflowLineHeight: 12,
                timestampHeight: 11
            )
        case .md:
            return Size(
                tileWidth: 364,
                tileHeight: 170,
                edgeInset: 10,
                sectionSpacing: 4,
                listItemCap: 6,
                maxCharts: 1,
                maxMetrics: 4,
                maxTextChars: 160,
                listRowHeight: 26,
                listTitleHeight: 14,
                chartPlotHeight: 40,
                chartHeightScale: 0.85,
                metricsHeight: 26,
                headerHeightNoSubtitle: 16,
                headerHeightWithSubtitle: 26,
                textHeight: 34,
                imageHeight: 16,
                spacerHeight: 4,
                progressHeight: 20,
                dividerHeight: 8,
                keyValueRowHeight: 18,
                badgesHeight: 22,
                titleChromeHeight: 16,
                overflowLineHeight: 12,
                timestampHeight: 11
            )
        case .lg:
            return Size(
                tileWidth: 364,
                tileHeight: 382,
                edgeInset: 14,
                sectionSpacing: 5,
                listItemCap: 10,
                maxCharts: 2,
                maxMetrics: 4,
                maxTextChars: 320,
                listRowHeight: 28,
                listTitleHeight: 14,
                chartPlotHeight: 72,
                chartHeightScale: 1,
                metricsHeight: 48,
                headerHeightNoSubtitle: 18,
                headerHeightWithSubtitle: 28,
                textHeight: 34,
                imageHeight: 16,
                spacerHeight: 4,
                progressHeight: 22,
                dividerHeight: 10,
                keyValueRowHeight: 20,
                badgesHeight: 24,
                titleChromeHeight: 18,
                overflowLineHeight: 12,
                timestampHeight: 11
            )
        case .xl:
            return Size(
                tileWidth: 748,
                tileHeight: 382,
                edgeInset: 14,
                sectionSpacing: 5,
                listItemCap: 14,
                maxCharts: 2,
                maxMetrics: 4,
                maxTextChars: 480,
                listRowHeight: 28,
                listTitleHeight: 14,
                chartPlotHeight: 84,
                chartHeightScale: 1,
                metricsHeight: 48,
                headerHeightNoSubtitle: 18,
                headerHeightWithSubtitle: 28,
                textHeight: 34,
                imageHeight: 16,
                spacerHeight: 4,
                progressHeight: 22,
                dividerHeight: 10,
                keyValueRowHeight: 20,
                badgesHeight: 24,
                titleChromeHeight: 18,
                overflowLineHeight: 12,
                timestampHeight: 11
            )
        }
    }
}
