# Agent Canvas — developer recipes
# https://github.com/casey/just
#
# Common day-to-day:
#   just run              # build+install if needed, launch app
#   just install          # rebuild + install to ~/Applications
#   just build-rust       # MCP binary (for Cursor/Claude)
#   just mcp-serve        # run MCP stdio server

set dotenv-load := false

root := justfile_directory()
macos := root / "platforms/macos"
ios := root / "platforms/ios"
install_dir := env_var_or_default("INSTALL_DIR", home_dir() / "Applications")

default:
    @just --list

# ── App shortcuts ───────────────────────────────────────────────────────────

# Build (if needed), install, and launch Agent Canvas
run: macos-install macos-run

# Rebuild + install only (no launch)
install: macos-install

# Launch installed app only (error if not installed)
open: macos-run

# Full reset + reinstall + launch (widget registration issues)
dev: macos-dev

# ── Rust / MCP ──────────────────────────────────────────────────────────────

# Build all Rust crates
build-rust:
    cargo build --manifest-path {{root}}/Cargo.toml

# Release MCP helper (embedded into AgentCanvas.app)
build-mcp-release:
    cargo build --manifest-path {{root}}/Cargo.toml -p agent-canvas-mcp --release

# Run unit tests
test:
    cargo test --manifest-path {{root}}/Cargo.toml

# Regenerate schema/canvas.schema.json from Rust
gen-schema:
    cargo run --quiet --manifest-path {{root}}/Cargo.toml -p agent-canvas-core --example gen_artifacts
    @echo "Wrote schema/canvas.schema.json and LayoutSpec.generated.swift"

# Alias: regenerate layout Swift constants (+ schema)
gen-layout-spec: gen-schema

# Regenerate schema/conformance goldens from the Rust reference packer
gen-conformance:
    cargo run --quiet --manifest-path {{root}}/Cargo.toml -p agent-canvas-core --example gen_conformance
    @echo "Wrote schema/conformance/*"

# Rust + (when on macOS) Swift packing conformance
conformance: test
    #!/usr/bin/env bash
    set -euo pipefail
    if [[ "$(uname -s)" != "Darwin" ]]; then
      echo "Swift conformance skipped (not macOS)"
      exit 0
    fi
    just macos-ensure-team
    just macos-gen
    xcodebuild \
      -project "{{macos}}/AgentCanvas.xcodeproj" \
      -scheme AgentCanvas \
      -configuration Debug \
      -destination 'platform=macOS,arch=arm64' \
      -derivedDataPath "{{root}}/build/macos" \
      CODE_SIGNING_ALLOWED=NO \
      test

# MCP stdio server (for Cursor / Claude Desktop)
mcp-serve *args:
    cargo run --manifest-path {{root}}/Cargo.toml -p agent-canvas-mcp -- {{args}}

# Print resolved canvas data paths
mcp-paths:
    cargo run --quiet --manifest-path {{root}}/Cargo.toml -p agent-canvas-mcp -- paths

# Cloud publish (debug MCP only — not in release app builds):
#   export AGENT_CANVAS_CLOUD_PUBLISH=1
#   export AGENT_CANVAS_API_URL=https://canvas.velox.test

# Seed sample content into a canvas (default: md-one)
mcp-seed canvas="md-one":
    cargo run --quiet --manifest-path {{root}}/Cargo.toml -p agent-canvas-mcp -- seed {{canvas}}

# Seed demos: where (size/slot) + what (content).
#   just seed-demos
#   just seed-demos md all bar
#   just seed-demos lg two pie
#   just seed-demos all all metrics
# content: themed|metrics|header|text|list|bar|line|pie|gauge|full
seed-demos size="all" slot="all" content="themed":
    #!/usr/bin/env bash
    set -euo pipefail
    size="{{size}}"; slot="{{slot}}"; content="{{content}}"
    size="${size#size=}"; slot="${slot#slot=}"; content="${content#content=}"
    cargo run --quiet --manifest-path "{{root}}/Cargo.toml" -p agent-canvas-mcp -- \
      seed-demos --size "$size" --slot "$slot" --content "$content"
    echo "Host open → reload ~1s. size=$size slot=$slot content=$content"

# ── macOS project ───────────────────────────────────────────────────────────

# Generate AgentCanvas.xcodeproj from project.yml (XcodeGen)
macos-gen:
    #!/usr/bin/env bash
    set -euo pipefail
    command -v xcodegen >/dev/null || { echo "Install XcodeGen: brew install xcodegen" >&2; exit 1; }
    cd "{{macos}}"
    xcodegen generate
    echo "Generated {{macos}}/AgentCanvas.xcodeproj"

# Write Config/Local.xcconfig with your Apple Team ID (required for widgets)
macos-team TEAM:
    #!/usr/bin/env bash
    set -euo pipefail
    cfg="{{macos}}/Config/Local.xcconfig"
    cat >"$cfg" <<EOF
    // Generated by just macos-team — gitignored
    DEVELOPMENT_TEAM = {{TEAM}}
    CODE_SIGN_STYLE = Automatic
    CODE_SIGN_IDENTITY = Apple Development
    CODE_SIGN_IDENTITY[sdk=macosx*] = Apple Development
    EOF
    echo "Wrote $cfg with DEVELOPMENT_TEAM={{TEAM}}"

# Detect or verify DEVELOPMENT_TEAM
macos-ensure-team:
    bash "{{root}}/scripts/macos/ensure-team.sh"

# Build + install to ~/Applications (reliable path for WidgetKit registration)
macos-install: build-mcp-release macos-ensure-team macos-gen
    bash "{{root}}/scripts/macos/install-app.sh"

# Developer ID sign + notarize + DMG for an already-built .app (default: ~/Applications).
# Prereq: CONFIGURATION=Release just macos-install
#         IDENTITY + NOTARY_PROFILE (or APPLE_API_KEY_*) in the environment
# Example:
#   IDENTITY="Developer ID Application: …" NOTARY_PROFILE=agent-canvas-notary \
#     just macos-notarize-dmg
# Override app path: APP=/path/to/AgentCanvas.app just macos-notarize-dmg
macos-notarize-dmg:
    #!/usr/bin/env bash
    set -euo pipefail
    APP="${APP:-{{install_dir}}/AgentCanvas.app}"
    if [[ -z "${IDENTITY:-}" ]]; then
      echo "error: set IDENTITY (Developer ID Application …)" >&2
      exit 1
    fi
    if [[ -z "${NOTARY_PROFILE:-}" && -z "${APPLE_API_KEY_PATH:-}" ]]; then
      echo "error: set NOTARY_PROFILE or APPLE_API_KEY_PATH (+ KEY_ID + ISSUER_ID)" >&2
      exit 1
    fi
    bash "{{root}}/scripts/macos/package-notarized-dmg.sh" "$APP"

# Build only (DerivedData under ./build/macos) — prefer macos-install for widgets
macos-build: build-mcp-release macos-ensure-team macos-gen
    #!/usr/bin/env bash
    set -euo pipefail
    BUILD_DIR="{{root}}/build/macos"
    mkdir -p "$BUILD_DIR"
    xcodebuild \
      -project "{{macos}}/AgentCanvas.xcodeproj" \
      -scheme AgentCanvas \
      -configuration Debug \
      -derivedDataPath "$BUILD_DIR" \
      -destination 'platform=macOS,arch=arm64' \
      -allowProvisioningUpdates \
      CODE_SIGN_STYLE=Automatic \
      build
    CONFIGURATION=Debug bash "{{root}}/scripts/macos/embed-mcp.sh" \
      "$BUILD_DIR/Build/Products/Debug/AgentCanvas.app"

# Launch the installed app (must install first). Prefer `just run` for install+launch.
macos-run:
    #!/usr/bin/env bash
    set -euo pipefail
    APP="{{install_dir}}/AgentCanvas.app"
    if [[ ! -d "$APP" ]]; then
      echo "App not installed at $APP — run: just install   (or just run)" >&2
      exit 1
    fi
    # Relaunch cleanly if already running
    if pgrep -x AgentCanvas >/dev/null 2>&1; then
      osascript -e 'tell application "AgentCanvas" to quit' 2>/dev/null || true
      sleep 0.4
      killall AgentCanvas 2>/dev/null || true
      sleep 0.2
    fi
    open "$APP"
    echo "Launched $APP"
    echo "Menu bar icon → Open Agent Canvas. Widgets: desktop → Edit Widgets → Agent Canvas"

# Open the Xcode project
macos-xcode: macos-gen
    open "{{macos}}/AgentCanvas.xcodeproj"

# Full cycle: reset registration state, reinstall, launch
macos-dev: macos-widgets-reset macos-install macos-run
    @echo ""
    @echo "If widgets still missing: just macos-diagnose"
    @echo "Then HARD_RESET=1 just macos-widgets-reset && just macos-install && just macos-run"

# ── iOS project ─────────────────────────────────────────────────────────────

# Generate AgentCanvasiOS.xcodeproj from project.yml (XcodeGen)
ios-gen:
    #!/usr/bin/env bash
    set -euo pipefail
    command -v xcodegen >/dev/null || { echo "Install XcodeGen: brew install xcodegen" >&2; exit 1; }
    cd "{{ios}}"
    xcodegen generate
    echo "Generated {{ios}}/AgentCanvasiOS.xcodeproj"

# Write Config/Local.xcconfig with your Apple Team ID
ios-team TEAM:
    #!/usr/bin/env bash
    set -euo pipefail
    cfg="{{ios}}/Config/Local.xcconfig"
    cat >"$cfg" <<EOF
    // Generated by just ios-team — gitignored
    DEVELOPMENT_TEAM = {{TEAM}}
    CODE_SIGN_STYLE = Automatic
    CODE_SIGN_IDENTITY = Apple Development
    EOF
    echo "Wrote $cfg with DEVELOPMENT_TEAM={{TEAM}}"

# Copy macOS Local.xcconfig team into iOS if present
ios-ensure-team:
    #!/usr/bin/env bash
    set -euo pipefail
    ios_cfg="{{ios}}/Config/Local.xcconfig"
    macos_cfg="{{macos}}/Config/Local.xcconfig"
    if [[ -f "$ios_cfg" ]] && grep -q 'DEVELOPMENT_TEAM' "$ios_cfg"; then
      echo "Using existing team in $ios_cfg"
      grep DEVELOPMENT_TEAM "$ios_cfg" || true
      exit 0
    fi
    if [[ -f "$macos_cfg" ]] && grep -q 'DEVELOPMENT_TEAM' "$macos_cfg"; then
      cp "$macos_cfg" "$ios_cfg"
      echo "Copied team from macOS Local.xcconfig → $ios_cfg"
      exit 0
    fi
    echo "error: no DEVELOPMENT_TEAM — run: just ios-team TEAM=XXXXXXXXXX" >&2
    exit 1

# Build for iOS Simulator
ios-build: ios-ensure-team ios-gen
    #!/usr/bin/env bash
    set -euo pipefail
    BUILD_DIR="{{root}}/build/ios"
    mkdir -p "$BUILD_DIR"
    xcodebuild \
      -project "{{ios}}/AgentCanvasiOS.xcodeproj" \
      -scheme AgentCanvasiOS \
      -configuration Debug \
      -derivedDataPath "$BUILD_DIR" \
      -destination 'generic/platform=iOS Simulator' \
      -allowProvisioningUpdates \
      CODE_SIGN_STYLE=Automatic \
      build

# Run unit tests (packing conformance) on Simulator
ios-test: ios-ensure-team ios-gen
    #!/usr/bin/env bash
    set -euo pipefail
    BUILD_DIR="{{root}}/build/ios"
    mkdir -p "$BUILD_DIR"
    # shellcheck disable=SC1091
    source "{{root}}/scripts/ios/pick-sim.sh"
    xcodebuild \
      -project "{{ios}}/AgentCanvasiOS.xcodeproj" \
      -scheme AgentCanvasiOS \
      -configuration Debug \
      -derivedDataPath "$BUILD_DIR" \
      -destination "platform=iOS Simulator,id=${IOS_SIM_UDID}" \
      -allowProvisioningUpdates \
      CODE_SIGN_STYLE=Automatic \
      test

# Open the iOS Xcode project
ios-xcode: ios-gen
    open "{{ios}}/AgentCanvasiOS.xcodeproj"

# Build + boot Simulator + install + launch
ios-run: ios-build
    #!/usr/bin/env bash
    set -euo pipefail
    BUILD_DIR="{{root}}/build/ios"
    APP=$(find "$BUILD_DIR/Build/Products" -name 'AgentCanvas.app' -path '*iphonesimulator*' | head -n1)
    if [[ -z "$APP" || ! -d "$APP" ]]; then
      echo "error: AgentCanvas.app not found under $BUILD_DIR" >&2
      exit 1
    fi
    # shellcheck disable=SC1091
    source "{{root}}/scripts/ios/pick-sim.sh"
    xcrun simctl boot "$IOS_SIM_UDID" 2>/dev/null || true
    open -a Simulator
    xcrun simctl install "$IOS_SIM_UDID" "$APP"
    xcrun simctl launch "$IOS_SIM_UDID" com.velox.agentcanvas.ios
    echo "Launched Agent Canvas on simulator $IOS_SIM_UDID"

# ── Widget registration reliability ─────────────────────────────────────────

# Diagnose why widgets may not appear
macos-diagnose:
    bash "{{root}}/scripts/macos/diagnose-widgets.sh"

# Reset widget registration state (containers + uninstall). Keeps AS canvas JSON.
macos-widgets-reset:
    bash "{{root}}/scripts/macos/reset-widgets.sh"

# Ask the running host to reload (// or seed + rely on watcher)
macos-reload:
    #!/usr/bin/env bash
    set -euo pipefail
    # Touch reload request so the host's 1s watcher reloads WidgetKit
    dir="$HOME/.velox/canvas"
    mkdir -p "$dir"
    printf 'md-one\n%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" >"$dir/.reload-request"
    echo "Wrote $dir/.reload-request — host app will reload within ~1s if running"

# ── Release ─────────────────────────────────────────────────────────────────

# Pre-tag checks: clean tree, menu/settings UX contract, CHANGELOG/version,
# Sparkle plist keys, Release build + Swift tests. Prints a short human smoke
# checklist afterward (menu bar walk). See .github/CI.md → Releasing.
#
#   just release-preflight
#   SKIP_BUILD=1 just release-preflight     # strings + git only
#   ALLOW_DIRTY=1 just release-preflight    # permit uncommitted changes
release-preflight:
    bash "{{root}}/scripts/macos/release-preflight.sh"

# ── Housekeeping ────────────────────────────────────────────────────────────

clean:
    #!/usr/bin/env bash
    set -euo pipefail
    rm -rf "{{root}}/target" "{{root}}/build"
    rm -rf "{{macos}}/AgentCanvas.xcodeproj"
    echo "Cleaned Rust target, build/, and generated xcodeproj"

# Cursor / Claude Desktop MCP snippet paths
mcp-config-snippet:
    #!/usr/bin/env bash
    set -euo pipefail
    BIN="{{root}}/target/debug/agent-canvas-mcp"
    echo "Build first: just build-rust"
    echo ""
    echo "Cursor / Claude Desktop mcpServers entry:"
    cat <<EOF
    {
      "mcpServers": {
        "agent-canvas": {
          "command": "$BIN",
          "args": ["stdio"]
        }
      }
    }
    EOF
