# Agent Canvas — developer recipes
# https://github.com/casey/just

set dotenv-load := false

root := justfile_directory()
macos := root / "platforms/macos"
install_dir := env_var_or_default("INSTALL_DIR", home_dir() / "Applications")

default:
    @just --list

# ── Rust / MCP ──────────────────────────────────────────────────────────────

# Build all Rust crates
build-rust:
    cargo build --manifest-path {{root}}/Cargo.toml

# Run unit tests
test:
    cargo test --manifest-path {{root}}/Cargo.toml

# MCP stdio server (for Cursor / Claude Desktop)
mcp-serve *args:
    cargo run --manifest-path {{root}}/Cargo.toml -p agent-canvas-mcp -- {{args}}

# Print resolved canvas data paths
mcp-paths:
    cargo run --quiet --manifest-path {{root}}/Cargo.toml -p agent-canvas-mcp -- paths

# Example: point MCP at local platform canvas service
#   export AGENT_CANVAS_API_URL=https://canvas.velox.test

# Seed sample content into a canvas (default: md-one)
mcp-seed canvas="md-one":
    cargo run --quiet --manifest-path {{root}}/Cargo.toml -p agent-canvas-mcp -- seed {{canvas}}

# Seed demos: where (size/slot) + what (content).
#   just seed-demos
#   just seed-demos md all bar
#   just seed-demos lg two pie
#   just seed-demos all all metrics
# content: themed|metrics|header|text|list|bar|line|pie|gauge|full
seed-demos size="all" slot="all" content="themed":
    #!/usr/bin/env bash
    set -euo pipefail
    size="{{size}}"; slot="{{slot}}"; content="{{content}}"
    size="${size#size=}"; slot="${slot#slot=}"; content="${content#content=}"
    cargo run --quiet --manifest-path "{{root}}/Cargo.toml" -p agent-canvas-mcp -- \
      seed-demos --size "$size" --slot "$slot" --content "$content"
    echo "Host open → reload ~1s. size=$size slot=$slot content=$content"

# ── macOS project ───────────────────────────────────────────────────────────

# Generate AgentCanvas.xcodeproj from project.yml (XcodeGen)
macos-gen:
    #!/usr/bin/env bash
    set -euo pipefail
    command -v xcodegen >/dev/null || { echo "Install XcodeGen: brew install xcodegen" >&2; exit 1; }
    cd "{{macos}}"
    xcodegen generate
    echo "Generated {{macos}}/AgentCanvas.xcodeproj"

# Write Config/Local.xcconfig with your Apple Team ID (required for widgets)
macos-team TEAM:
    #!/usr/bin/env bash
    set -euo pipefail
    cfg="{{macos}}/Config/Local.xcconfig"
    cat >"$cfg" <<EOF
    // Generated by just macos-team — gitignored
    DEVELOPMENT_TEAM = {{TEAM}}
    CODE_SIGN_STYLE = Automatic
    CODE_SIGN_IDENTITY = Apple Development
    CODE_SIGN_IDENTITY[sdk=macosx*] = Apple Development
    EOF
    echo "Wrote $cfg with DEVELOPMENT_TEAM={{TEAM}}"

# Detect or verify DEVELOPMENT_TEAM
macos-ensure-team:
    bash "{{root}}/scripts/macos/ensure-team.sh"

# Build + install to ~/Applications (reliable path for WidgetKit registration)
macos-install: macos-ensure-team macos-gen
    bash "{{root}}/scripts/macos/install-app.sh"

# Build only (DerivedData under ./build/macos) — prefer macos-install for widgets
macos-build: macos-ensure-team macos-gen
    #!/usr/bin/env bash
    set -euo pipefail
    BUILD_DIR="{{root}}/build/macos"
    mkdir -p "$BUILD_DIR"
    xcodebuild \
      -project "{{macos}}/AgentCanvas.xcodeproj" \
      -scheme AgentCanvas \
      -configuration Debug \
      -derivedDataPath "$BUILD_DIR" \
      -destination 'platform=macOS,arch=arm64' \
      -allowProvisioningUpdates \
      CODE_SIGN_STYLE=Automatic \
      build

# Launch the installed app (must install first)
macos-run:
    #!/usr/bin/env bash
    set -euo pipefail
    APP="{{install_dir}}/AgentCanvas.app"
    if [[ ! -d "$APP" ]]; then
      echo "App not installed at $APP — run: just macos-install" >&2
      exit 1
    fi
    open "$APP"
    echo "Launched $APP"
    echo "Add widgets: right-click desktop → Edit Widgets → “Agent Canvas”"

# Open the Xcode project
macos-xcode: macos-gen
    open "{{macos}}/AgentCanvas.xcodeproj"

# Full cycle: reset registration state, reinstall, launch
macos-dev: macos-widgets-reset macos-install macos-run
    @echo ""
    @echo "If widgets still missing: just macos-diagnose"
    @echo "Then HARD_RESET=1 just macos-widgets-reset && just macos-install && just macos-run"

# ── Widget registration reliability ─────────────────────────────────────────

# Diagnose why widgets may not appear
macos-diagnose:
    bash "{{root}}/scripts/macos/diagnose-widgets.sh"

# Reset widget registration state (containers + uninstall). Keeps AS canvas JSON.
macos-widgets-reset:
    bash "{{root}}/scripts/macos/reset-widgets.sh"

# Ask the running host to reload (// or seed + rely on watcher)
macos-reload:
    #!/usr/bin/env bash
    set -euo pipefail
    # Touch reload request so the host's 1s watcher reloads WidgetKit
    dir="$HOME/.velox/canvas"
    mkdir -p "$dir"
    printf 'md-one\n%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" >"$dir/.reload-request"
    echo "Wrote $dir/.reload-request — host app will reload within ~1s if running"

# ── Housekeeping ────────────────────────────────────────────────────────────

clean:
    #!/usr/bin/env bash
    set -euo pipefail
    rm -rf "{{root}}/target" "{{root}}/build"
    rm -rf "{{macos}}/AgentCanvas.xcodeproj"
    echo "Cleaned Rust target, build/, and generated xcodeproj"

# Cursor / Claude Desktop MCP snippet paths
mcp-config-snippet:
    #!/usr/bin/env bash
    set -euo pipefail
    BIN="{{root}}/target/debug/agent-canvas-mcp"
    echo "Build first: just build-rust"
    echo ""
    echo "Cursor / Claude Desktop mcpServers entry:"
    cat <<EOF
    {
      "mcpServers": {
        "agent-canvas": {
          "command": "$BIN",
          "args": ["stdio"]
        }
      }
    }
    EOF
