package dev.velox.agentcanvas.canvas

/**
 * Portable layout constants from Rust `layout_spec` / Apple `LayoutSpec.generated.swift`.
 * Used by both Compose preview and Glance packing so density matches the other shells.
 */
object LayoutSpec {
    val dropPriority: Map<String, Int> = mapOf(
        "header" to 10,
        "metrics" to 20,
        "list" to 40,
        "chart" to 30,
        "text" to 50,
        "image" to 60,
        "spacer" to 70,
        "progress" to 45,
        "divider" to 75,
        "keyValue" to 42,
        "badges" to 48,
        "icon" to 47,
        "group" to 55,
    )

    val packRank: Map<String, Int> = mapOf(
        "header" to 0,
        "metrics" to 1,
        "list" to 2,
        "chart" to 3,
        "text" to 4,
        "image" to 5,
        "spacer" to 6,
        "progress" to 4,
        "divider" to 6,
        "keyValue" to 2,
        "badges" to 4,
        "icon" to 4,
        "group" to 2,
    )

    data class Size(
        val tileWidth: Float,
        val tileHeight: Float,
        val edgeInset: Float,
        val sectionSpacing: Float,
        val listItemCap: Int,
        val maxCharts: Int,
        val maxMetrics: Int,
        val maxTextChars: Int,
        val listRowHeight: Float,
        val listTitleHeight: Float,
        val chartPlotHeight: Float,
        val chartHeightScale: Float,
        val metricsHeight: Float,
        val headerHeightNoSubtitle: Float,
        val headerHeightWithSubtitle: Float,
        val textHeight: Float,
        val imageHeightSmall: Float,
        val imageHeightMedium: Float,
        val imageHeightLarge: Float,
        val spacerHeight: Float,
        val progressHeight: Float,
        val dividerHeight: Float,
        val keyValueRowHeight: Float,
        val badgesHeight: Float,
        val iconHeightSm: Float,
        val iconHeightMd: Float,
        val iconHeightLg: Float,
        val titleChromeHeight: Float,
        val overflowLineHeight: Float,
        val timestampHeight: Float,
    )

    fun size(s: CanvasSize): Size = when (s) {
        CanvasSize.Small -> Size(
            tileWidth = 170f,
            tileHeight = 170f,
            edgeInset = 12f,
            sectionSpacing = 5f,
            listItemCap = 5,
            maxCharts = 0,
            maxMetrics = 2,
            maxTextChars = 80,
            listRowHeight = 16f,
            listTitleHeight = 14f,
            chartPlotHeight = 36f,
            chartHeightScale = 0.9f,
            metricsHeight = 26f,
            headerHeightNoSubtitle = 16f,
            headerHeightWithSubtitle = 24f,
            textHeight = 26f,
            imageHeightSmall = 40f,
            imageHeightMedium = 60f,
            imageHeightLarge = 80f,
            spacerHeight = 4f,
            progressHeight = 18f,
            dividerHeight = 8f,
            keyValueRowHeight = 16f,
            badgesHeight = 20f,
            iconHeightSm = 18f,
            iconHeightMd = 24f,
            iconHeightLg = 32f,
            titleChromeHeight = 16f,
            overflowLineHeight = 12f,
            timestampHeight = 11f,
        )
        CanvasSize.Medium -> Size(
            tileWidth = 364f,
            tileHeight = 170f,
            edgeInset = 10f,
            sectionSpacing = 4f,
            listItemCap = 6,
            maxCharts = 1,
            maxMetrics = 4,
            maxTextChars = 160,
            listRowHeight = 26f,
            listTitleHeight = 14f,
            chartPlotHeight = 40f,
            chartHeightScale = 0.85f,
            metricsHeight = 26f,
            headerHeightNoSubtitle = 16f,
            headerHeightWithSubtitle = 26f,
            textHeight = 34f,
            imageHeightSmall = 44f,
            imageHeightMedium = 72f,
            imageHeightLarge = 110f,
            spacerHeight = 4f,
            progressHeight = 20f,
            dividerHeight = 8f,
            keyValueRowHeight = 18f,
            badgesHeight = 22f,
            iconHeightSm = 20f,
            iconHeightMd = 28f,
            iconHeightLg = 36f,
            titleChromeHeight = 16f,
            overflowLineHeight = 12f,
            timestampHeight = 11f,
        )
        CanvasSize.Large -> Size(
            tileWidth = 364f,
            tileHeight = 382f,
            edgeInset = 14f,
            sectionSpacing = 5f,
            listItemCap = 10,
            maxCharts = 2,
            maxMetrics = 4,
            maxTextChars = 320,
            listRowHeight = 28f,
            listTitleHeight = 14f,
            chartPlotHeight = 72f,
            chartHeightScale = 1f,
            metricsHeight = 48f,
            headerHeightNoSubtitle = 18f,
            headerHeightWithSubtitle = 28f,
            textHeight = 34f,
            imageHeightSmall = 56f,
            imageHeightMedium = 96f,
            imageHeightLarge = 150f,
            spacerHeight = 4f,
            progressHeight = 22f,
            dividerHeight = 10f,
            keyValueRowHeight = 20f,
            badgesHeight = 24f,
            iconHeightSm = 22f,
            iconHeightMd = 32f,
            iconHeightLg = 44f,
            titleChromeHeight = 18f,
            overflowLineHeight = 12f,
            timestampHeight = 11f,
        )
    }
}
